
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 07 14:52:51 CST 2018
//----------------------------------------------------

package minicsharplex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAJOREQ = 10;
  public static final int READLINE = 48;
  public static final int MINOREQ = 8;
  public static final int READINT = 47;
  public static final int ENTERO = 51;
  public static final int DOUBLE = 29;
  public static final int NOTEQUAL = 13;
  public static final int PARENIZQ = 22;
  public static final int INTERFACE = 33;
  public static final int LLAVEDER = 25;
  public static final int INT = 28;
  public static final int HEX = 50;
  public static final int MINOR = 7;
  public static final int FOR = 38;
  public static final int MINUS = 3;
  public static final int SEMICOLON = 17;
  public static final int AND = 14;
  public static final int CORCHIZQ = 20;
  public static final int OR = 15;
  public static final int BOOL = 30;
  public static final int COMMA = 18;
  public static final int CLASS = 32;
  public static final int DIV = 5;
  public static final int MAJOR = 9;
  public static final int NEWARRAY = 45;
  public static final int PLUS = 2;
  public static final int IF = 40;
  public static final int GETBYTE = 56;
  public static final int THIS = 35;
  public static final int SETBYTE = 57;
  public static final int BOOLEAN = 52;
  public static final int EOF = 0;
  public static final int RETURN = 42;
  public static final int EQUAL = 12;
  public static final int NEW = 44;
  public static final int error = 1;
  public static final int CADENA = 53;
  public static final int NULL = 34;
  public static final int MOD = 6;
  public static final int BREAK = 43;
  public static final int PARENDER = 23;
  public static final int VOID = 27;
  public static final int ADMIRATION = 16;
  public static final int ASIGNATION = 11;
  public static final int DOBLE = 54;
  public static final int ELSE = 41;
  public static final int CORCHDER = 21;
  public static final int POINT = 19;
  public static final int WHILE = 39;
  public static final int LLAVEIZQ = 24;
  public static final int EXTENDS = 36;
  public static final int MULTI = 4;
  public static final int STRING = 31;
  public static final int MALLOC = 49;
  public static final int IMPLEMENTS = 37;
  public static final int CORCHDOBLE = 26;
  public static final int PRINT = 46;
  public static final int IDENTIFIER = 55;
}

