
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 22 12:35:38 CST 2018
//----------------------------------------------------

package minicsharplex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAJOREQ = 13;
  public static final int READLINE = 51;
  public static final int MINOREQ = 11;
  public static final int READINT = 50;
  public static final int ENTERO = 54;
  public static final int DOUBLE = 32;
  public static final int NOTEQUAL = 16;
  public static final int PARENIZQ = 25;
  public static final int INTERFACE = 36;
  public static final int LLAVEDER = 28;
  public static final int INT = 31;
  public static final int HEX = 53;
  public static final int MINOR = 10;
  public static final int FOR = 41;
  public static final int MINUS = 5;
  public static final int CONSTANTE = 6;
  public static final int SEMICOLON = 20;
  public static final int AND = 17;
  public static final int CORCHIZQ = 23;
  public static final int ARCHIVO = 3;
  public static final int OR = 18;
  public static final int BOOL = 33;
  public static final int COMMA = 21;
  public static final int CLASS = 35;
  public static final int DIV = 8;
  public static final int MAJOR = 12;
  public static final int NEWARRAY = 48;
  public static final int PLUS = 4;
  public static final int IF = 43;
  public static final int GETBYTE = 59;
  public static final int THIS = 38;
  public static final int SETBYTE = 60;
  public static final int BOOLEAN = 55;
  public static final int EOF = 0;
  public static final int RETURN = 45;
  public static final int EQUAL = 15;
  public static final int NEW = 47;
  public static final int error = 1;
  public static final int INCLUDE = 2;
  public static final int CADENA = 56;
  public static final int NULL = 37;
  public static final int MOD = 9;
  public static final int BREAK = 46;
  public static final int PARENDER = 26;
  public static final int VOID = 30;
  public static final int ADMIRATION = 19;
  public static final int ASIGNATION = 14;
  public static final int DOBLE = 57;
  public static final int ELSE = 44;
  public static final int CORCHDER = 24;
  public static final int POINT = 22;
  public static final int WHILE = 42;
  public static final int LLAVEIZQ = 27;
  public static final int EXTENDS = 39;
  public static final int MULTI = 7;
  public static final int STRING = 34;
  public static final int MALLOC = 52;
  public static final int IMPLEMENTS = 40;
  public static final int CORCHDOBLE = 29;
  public static final int PRINT = 49;
  public static final int IDENTIFIER = 58;
}

