
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 18 22:00:19 CST 2018
//----------------------------------------------------

package minicsharplex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAJOREQ = 12;
  public static final int READLINE = 50;
  public static final int MINOREQ = 10;
  public static final int READINT = 49;
  public static final int ENTERO = 53;
  public static final int DOUBLE = 31;
  public static final int NOTEQUAL = 15;
  public static final int PARENIZQ = 24;
  public static final int INTERFACE = 35;
  public static final int LLAVEDER = 27;
  public static final int INT = 30;
  public static final int HEX = 52;
  public static final int MINOR = 9;
  public static final int FOR = 40;
  public static final int MINUS = 5;
  public static final int SEMICOLON = 19;
  public static final int AND = 16;
  public static final int CORCHIZQ = 22;
  public static final int ARCHIVO = 3;
  public static final int OR = 17;
  public static final int BOOL = 32;
  public static final int COMMA = 20;
  public static final int CLASS = 34;
  public static final int DIV = 7;
  public static final int MAJOR = 11;
  public static final int NEWARRAY = 47;
  public static final int PLUS = 4;
  public static final int IF = 42;
  public static final int GETBYTE = 58;
  public static final int THIS = 37;
  public static final int SETBYTE = 59;
  public static final int BOOLEAN = 54;
  public static final int EOF = 0;
  public static final int RETURN = 44;
  public static final int EQUAL = 14;
  public static final int NEW = 46;
  public static final int error = 1;
  public static final int INCLUDE = 2;
  public static final int CADENA = 55;
  public static final int NULL = 36;
  public static final int MOD = 8;
  public static final int BREAK = 45;
  public static final int PARENDER = 25;
  public static final int VOID = 29;
  public static final int ADMIRATION = 18;
  public static final int ASIGNATION = 13;
  public static final int DOBLE = 56;
  public static final int ELSE = 43;
  public static final int CORCHDER = 23;
  public static final int POINT = 21;
  public static final int WHILE = 41;
  public static final int LLAVEIZQ = 26;
  public static final int EXTENDS = 38;
  public static final int MULTI = 6;
  public static final int STRING = 33;
  public static final int MALLOC = 51;
  public static final int IMPLEMENTS = 39;
  public static final int CORCHDOBLE = 28;
  public static final int PRINT = 48;
  public static final int IDENTIFIER = 57;
}

